"""adds hashed_password to therapists

Revision ID: 242d969d27d7
Revises: d25a614e6fc5
Create Date: 2025-11-13 12:55:49.778554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242d969d27d7'
down_revision: Union[str, Sequence[str], None] = 'd25a614e6fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapists', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'hashed_password')
    # ### end Alembic commands ###
