"""change_patient_date_of_birth_to_date

Revision ID: 91ac7c8e2f17
Revises: 242d969d27d7
Create Date: 2025-11-13 16:32:03.766651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ac7c8e2f17'
down_revision: Union[str, Sequence[str], None] = '242d969d27d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
