"""Added reset password token to therapists

Revision ID: e4febd4a32e5
Revises: 91ac7c8e2f17
Create Date: 2025-11-14 07:36:42.623709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4febd4a32e5'
down_revision: Union[str, Sequence[str], None] = '91ac7c8e2f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapists', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('therapists', sa.Column('password_reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'password_reset_token_expires_at')
    op.drop_column('therapists', 'password_reset_token')
    # ### end Alembic commands ###
